default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['BACKEND_DB_HOST'] %>
  database: joko
  password:
  username: joko
  port: <%= ENV['BACKEND_DB_PORT'] %>

development:
  <<: *default
test:
  <<: *default
  database: uft_test

production:
  <<: *default
