default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['BACKEND_DB_HOST'] %>
  database: <%= ENV['BACKEND_DB_NAME'] %>
  password: <%= ENV['BACKEND_DB_PASSWORD'] %>
  username: <%= ENV['BACKEND_DB_USER'] %>
  port: <%= ENV['BACKEND_DB_PORT'] %>

development:
  <<: *default
test:
  <<: *default
  database: uft_test

production:
  <<: *default
